{ pkgs }: {
  deps = [
    pkgs.flutter
    pkgs.autorandr
    pkgs.haskellPackages.gogol-androidmanagement
    pkgs.arandr
    pkgs.haskellPackages.gogol-android-enterprise
    pkgs.emacs27Packages.android-env
    pkgs.androidStudioPackages.stable
    pkgs.androidStudioPackages.canary
    pkgs.androidStudioPackages.beta
    pkgs.python39Packages.androidtv
    pkgs.android-tools
    pkgs.python38Packages.androguard
    pkgs.emacs27Packages.android-mode
    pkgs.android-file-transfer
    pkgs.android-studio
    pkgs.haskellPackages.android-lint-summary
    pkgs.haskellPackages.AndroidViewHierarchyImporter
    pkgs.dotnet-sdk_2
    pkgs.npapi_sdk
    pkgs.dotnet-sdk
    pkgs.openjfx15
    pkgs.operator-sdk
    pkgs.python38Packages.aws-xray-sdk
    pkgs.pico-sdk
    pkgs.dotnetCorePackages.sdk_3_0
    pkgs.aws-sdk-cpp
    pkgs.openjfx11
    pkgs.intel-media-sdk
    pkgs.apache-flex-sdk
    pkgs.dotnetCorePackages.sdk_5_0
    pkgs.ladspa-sdk
    pkgs.spdk
    pkgs.wineStaging
    pkgs.win-virtio
    pkgs.winePackages.fonts
    pkgs.dell-530cdn
    pkgs.haskellPackages.debian-binary
    pkgs.flutter316
    pkgs.cowsay
  ];
}